### ISSUE TITLE
update channel logos

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/sushi-chef-khan-academy#12]
Currently we're using various versions of the old logo:

![image](https://user-images.githubusercontent.com/2367265/57797318-05597e80-76ff-11e9-8896-3bdfabb86a68.png)

We should be using the new one.

Resources:

* https://khanacademy.zendesk.com/hc/en-us/articles/202263034-What-is-Khan-Academy-s-Trademark-and-Brand-Usage-Policy-
* https://docs.google.com/presentation/d/1WAxXM7Y9UVhMpv5rgCpDmM17hOY-orszWgjzJ9AOVJo/edit#slide=id.g3388f78a0c_2_654
* https://www.dropbox.com/sh/dxvxschzgq3kgmz/AAAFQTV8nnOUZzK1w1tcg56la?dl=0

**Comment by ivanistheone** [comment]
@ralphiee22  Here are 16:9 images of the logo that could be used for chef:

Force white background:
![khan-academy-logo__white_bg](https://user-images.githubusercontent.com/163966/57798700-52e3e480-771b-11e9-8223-9a5b2181b693.png)


[use view image | save as]

**Comment by indirectlylit** [comment]
that looks fine to me.

Out of curiosity, do we have a guideline indicating that channel thumbnails should have text in them? It seems a bit redundant with the channel name, and then we could just use the graphical part of the logo

**Comment by kollivier** [comment]
I thought our policy was to use square aspect ratio for the channel icons, and 16:9 for content node icons? Has this changed?

**Comment by indirectlylit** [comment]
I think the most recent threads were: 

* https://learningequality.slack.com/archives/C0LKG14NL/p1549897106005600
* https://learningequality.slack.com/archives/C0LK8QS9J/p1551919364051500

**Comment by kollivier** [comment]
Okay, I'm going to check with @jayoshih about making this change. Right now Studio will crop icons to square on publish. I was going to change that for contentnode thumbnails, but it would actually simplify things if we make it consistently resize to 16:9 for all thumbnails.

**Comment by indirectlylit** [comment]
Cool. In that thread I'd mentioned having a shared Vue component for consistent rendering of arbitrarily-sized thumbnails within a 16:9 viewport using letterboxing. Let me know if that's a priority and I can try to bang out an initial version.

**Comment by ivanistheone** [comment]
Updated PR with [square-aspect ratio logo](https://github.com/learningequality/sushi-chef-khan-academy/pull/13/commits/34c8f3941024b7f7fd64464c0f5ec3d1842b989a?short_path=e29ef83#diff-e29ef8388c3b9af8e9061f1dc19e7391). This way currently looks good in Studio. Kolibri adds whitespace on the sides when displaying 16:9 so will also look good in Kolibri too.

I intially went with 16:9 because "primary" logo is VERY wide so would have been too small in square format, but secondary logo is better choice since 1) works well on Studio and Kolibri in current setup, and 2) doesn't duplicate the "Khan Academy" titleing.

**Comment by ivanistheone** [comment]
This has been fixed for some time now; new runs will use the [latest logo](https://github.com/learningequality/sushi-chef-khan-academy/blob/master/chefdata/khan-academy-logo.png). Some of the old logos are still present on channels that haven't been updated recently, but will get phased out over time.
