### ISSUE TITLE
Information request for TSV files

### ISSUE THREAD

**Issue by imnitishng** [learningequality/sushi-chef-khan-academy#30]
Hello! @ivanistheone
I'd like to know more about the source of the TSV files that are used here https://github.com/learningequality/sushi-chef-khan-academy/blob/582d6d02d42332f6694416c4f7398b938075ca25/tsvkhan.py#L27

I see that the TSV files were updated regularly on GCP so I wanted to explore the source scripts since the API for Khan academy lacks proper documentation and does not work anymore as I observed in the `main` branch of the project.
I tried digging into [content-automation-scripts](https://github.com/learningequality/content-automation-scripts) (I assume this is responsible for uploading the files to GCP) but couldn't find much. 
Is the code for the creation of these files available somewhere? 
Or are these files provided by Khan Academy?

**Comment by rtibbles** [comment]
Yes, these files are provided by Khan Academy.
