### ISSUE TITLE
Should we skip CS topic since material is missing?

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/sushi-chef-khan-academy#5]
Since `scratchpad`s are not supported, much of the CS curriculum on KA is missing.

We still have a folder for it though and it shows up in the public channels:
<img width="1126" alt="screen shot 2018-10-13 at 5 31 22 am" src="https://user-images.githubusercontent.com/163966/46954904-b27ff180-d05f-11e8-9bce-7d656509fa34.png">
see [studio](https://studio.learningequality.org/channels/878ec2e6f88c5c268b1be6f202833cd4/view/f4e7e1b)

This might lead to disappointed users who look through the topic and don't find any actual material, or to false-alarm support requests: "Hey I imported KA-fr but I don't see the computer science videos" can you fix this?

Possible solutions:
  1. do not include the CS subfolder to avoid confusion
  2. add support for `scratchpad` [in the long term]

**Comment by ralphiee22** [comment]
Immediate solution is to exclude the CS subfolder as there is missing/incomplete content.
We can revisit supporting scratchpad in the perseus renderer at a later time. cc: @rtibbles

**Comment by ralphiee22** [comment]
resolved here https://github.com/learningequality/sushi-chef-khan-academy/commit/8a960046c689989c0f38903fc75ad6953b09c43f
