### ISSUE TITLE
Certain videos from KA cdn have low audio quality

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/sushi-chef-khan-academy#7]
Certain KA videos have "muffled" sound. The problem is the the original source file we get from the KA API, e.g. https://cdn.kastatic.org/KA-youtube-converted/Rd4a1X3B61w.mp4-low/Rd4a1X3B61w-low.mp4

This file has Audio: aac (LC) (mp4a ), 8000 Hz, mono, fltp, 35 kb/s settings for some reason.

Context:
  1. http://community.learningequality.org/t/audio-quality-concerns-using-kolibri/934
  2. KA bulgarian [sample video with bad quality](http://35.198.171.164/learn/#/topics/c/72459c1cbf805eb494abce32da144cfa)

Possible solutions would be to use a higher-quality format option form the API or get form youtube.

**Comment by ralphiee22** [comment]
so then the video will still have a muffled sound even if we download them from a higher resolution version?
https://cdn.kastatic.org/KA-youtube-converted/Rd4a1X3B61w.mp4/Rd4a1X3B61w.mp4

**Comment by ivanistheone** [comment]
@ralphiee22 High res video seems to have good audio 44.1khz:

```
    Stream #0:0(und): Video: h264 (Constrained Baseline) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 795 kb/s, 30 fps, 30 tbr, 30 tbn, 60 tbc (default)
    Stream #0:1(und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, mono, fltp, 46 kb/s (default)
```

Obtained via:
  1. `wget "https://cdn.kastatic.org/KA-youtube-converted/Rd4a1X3B61w.mp4/Rd4a1X3B61w.mp4"`
  2. `ffprobe Rd4a1X3B61w.mp4`

**Comment by ralphiee22** [comment]
Does running the pressurecooker compression degrade the audio quality, or only the video resolution, or both?

**Comment by ivanistheone** [comment]
Pressurecooker `--compress` does a 32kb/sec rate limit for audio too, but that does not lead to noticeable quality degradation. [I [previously](https://github.com/learningequality/pressurecooker/issues/20) thought the 32k limit was the cause, but after some tests realized that's not it]

**Comment by indirectlylit** [comment]
another report of low quality audio: https://github.com/learningequality/kolibri/issues/5466

**Comment by ArthurMafra** [comment]
I do also have very poor video and audio quality on kolibri that makes it impossible to use. Ka Lite does not suffer from it and downlaod with pretty good quality. Is it possible to disable encoding?

**Comment by ivanistheone** [comment]
We have found the root cause and developed a fix the video quality issues.

**Cause:** The bad video quality problems were caused by upstream source problems (for efficiency we were downloading pre-compressed videos from KA servers, some of which had very low video and audio quality).

**Fix:** Stop using these pre-compressed video files, and instead download the 480-resolution videos directly from youtube. An additional lightweight post-processing step is applied to the videos to compress audio track to 32kbps, mono.

Example old video: https://kolibri-catalog-en.learningequality.org/en/learn/#/topics/c/ae717c0d89b25770ba031f68075eba5c

Example new video: https://kolibri-catalog-en.learningequality.org/en/learn/#/topics/c/c14e2df589ce522bb038370ebc389fbc

This improvement in video quality causes around 50% increase in file size (e.g. the above examples, the video file changes from 3MB to 4.7MB), which means the Khan Academy English channel will increase in size from 47GB to around 70GB.

Over the next months we'll be rolling out the fixed video updates to all KA channels in the following order:
 - [Khan Academy (English - US curriculum)](https://kolibri-catalog-en.learningequality.org/en/learn/#/topics/c9d7f950ab6b5a1199e3d6c10d7f0103) [c9d7f950ab6b5a1199e3d6c10d7f0103] = a new channel with the same content as old Khan Academy English channel but without extra content for India curriculum.
 - **Khan Academy (Espanol)**
 - **Khan Academy (Francais)**
 - **Khan Academy (Portuges (Brazil))**
 - **Khan Academy (English - India curriculum)** = KA English channel with no US-curriculum, and India curriculum
- ... all the others

The main **Khan Academy (English)** channel will be updated last (to avoid surprising users with a forced download 70GB of videos). Until then users interested in accessing the high resolution videos can download the new channel [Khan Academy (English - US curriculum)](https://kolibri-catalog-en.learningequality.org/en/learn/#/topics/c9d7f950ab6b5a1199e3d6c10d7f0103) 
(channel_id = c9d7f950ab6b5a1199e3d6c10d7f0103).

**Comment by indirectlylit** [comment]
FYI - https://github.com/learningequality/kolibri/issues/3834 is one of our highest-traffic pages:

![image](https://user-images.githubusercontent.com/2367265/82933652-1c9c9000-9f3f-11ea-8f3c-d51d5710b04e.png)

I assume that's due to H.264?

**Comment by ivanistheone** [comment]
This issue is now resolved.

For accessing KA English channel with better quality videos, import one of the following channels:
 - [Khan Academy (English - US curriculum)](https://kolibri-catalog-en.learningequality.org/en/learn/#/topics/c9d7f950ab6b5a1199e3d6c10d7f0103) -- main English channel from https://www.khanacademy.org/ 
 - [Khan Academy (English - CBSE India Curriculum)](https://kolibri-catalog-hi.learningequality.org/hi-in/learn/#/topics/2fd54ca47a8f59c99fcefaaa3894c19e) -- similar to the above but also contains course materials aligned to India curriculum

The old channel KA channel will not be updated so as not to force users to download a very large update (every single video would have to be re-imported).
