### ISSUE TITLE
curriculum-aligned content is making the main KA English channel confusing

### ISSUE THREAD

**Issue by indirectlylit** [learningequality/sushi-chef-khan-academy#8]
Users attempting to import content from KA English will see lots of topics like this:

![image](https://user-images.githubusercontent.com/2367265/51502802-9e4d3e00-1d8c-11e9-9963-1063250b9eb0.png)

Even if the user skips these topics, they still appear in Kolibri due to learningequality/kolibri#4082

This is particularly problematic because the curriculum-aligned items seem ordered above the KA-organized topics:

![image](https://user-images.githubusercontent.com/2367265/51502854-dd7b8f00-1d8c-11e9-823c-06d43b6a4e5e.png)

----

cc @ralphiee22 @jamalex

**Comment by indirectlylit** [comment]
https://github.com/learningequality/kolibri/issues/4082 is addressed now, so this issue is mitigated.

However, these India-specific folders should still be migrated to a separate channel  specifically for Indian curriculum alignment

**Comment by ivanistheone** [comment]
This is fixed now, with India specific folders in a separate channel: https://kolibri-catalog-hi.learningequality.org/hi-in/learn/#/topics/2fd54ca47a8f59c99fcefaaa3894c19e
